### ISSUE TITLE
Language choice and parallelization tool

### ISSUE THREAD

**Issue by davidek** [blindstore/blindstore#1]
Because the main issue with the current prototype is performance, we should re-consider using only python for implementig the protocol functions. Some brainstorming lead to several proposals:
# Language choice

(to be matched with the parallelization choice)

Priority is on ease to write and maintain
- Stick with Python and C
- Rust  (by Mozilla)
- Go (by Google)
- C++ (much less likely)
- Scala/Java (there's [fhe-core](https://github.com/kryptnostic/fhe-core) library for FHE)
- Other solutions?
# Parallelizing tool

(to be matched with the language choice)
- Hadoop
- Apache Storm – any language
- Apache Spark – Python, Scala or Java
- Other solutions?

**Comment by bogdan-kulynych** [comment]
If we stick with Python, we could use [Hadoop streaming, mrjob, or dumbo](http://blog.cloudera.com/blog/2013/01/a-guide-to-python-frameworks-for-hadoop/), for example. For reference, see how you write jobs with [mrjob](https://pythonhosted.org/mrjob/guides/why-mrjob.html). Then, with mrjob you can deploy on local Hadoop clusters or Amazon Mapreduce.

First, we need to research if we need MapReduce at this point. So, try vectorizing code first and measure the performance, also see if Python-C communication overhead is significant enough to go native.

**Comment by andronat** [comment]
Hello, just FYI, I believe that [Apache Spark](https://spark.apache.org) is more convenient for the situation.

**Comment by bogdan-kulynych** [comment]
Yep, so I've added a Scala option using [fhe-core](https://github.com/kryptnostic/fhe-core) library. It would probably be convenient to use Spark with Scala. 

I've looked at Spark and it looks like it suits our needs, because we need data parallelization (the simultaneous execution on multiple cores of the same function across the elements of a dataset).

**Comment by andronat** [comment]
Unfortunately Spark doesn't support other languages except Python, Java and Scala. There was a way to pass results on other languages though pipes (like Hadoop Streaming pipes) on older versions (see Spark 0.8) but the current version doesn't seems to support them (1.0.1).

But spark can write results on filesystem, thus a hybrid model of languages collaborating thought files, can be done. Though this may result into maintenance problems in the future.

**Comment by HarryCutts** [comment]
After the meeting on Monday, it was decided that @bogdan-kulynych and @andronat will work on an implementation in Scala and Apache Spark.

**Comment by OmeGak** [comment]
We are now using top-notch C++. YAY!!
