### ISSUE TITLE
Code parallelization

### ISSUE THREAD

**Issue by andronat** [blindstore/blindstore#10]
Today me, @bogdan-kulynych and @northdpole we had a long conversation about parallelization and optimizations. We broke the code into steps and we concluded on how we should proceed with the subject.

What we found:
- The XOR operation between the clients' encrypted key and the encrypted vector of 1's, can be moved on the client side
- We can optimize a lot the needed space for the calculation matrices
- All intermediate data seems to be independent and thus we can parallelize in a high degree.

How we proceed:
- Create flexible benchmarking scripts that will create test input date
- Test each part of the algorithm with different sizes of input to find bottlenecks

**Comment by Eipifi** [comment]
The server code needs the encrypted bits of the query as well as the negated encrypted bits, therefore moving the XOR to the client is not necessary There are literally 32 XOR operations you need to do in gamma() phase, no matter how many rows you have. Assuming you got 32-bit identifiers.

Today I noticed that reusing encrypted bits in gamma phase has a very positive side effect - essentially, all AND operations are made on the same EncryptedBit **objects**. This makes it very easy to cache the AND results. I managed to squeeze 1000 gammas in 30 seconds on a single thread just by avoiding performing the same operation twice.

The same trick can be done with the R() phase, although there you have to cache the results of XORing as many gammas as there are rows. On my local machine I am able to perform queries on 20x20 db in less than 2 seconds. Tomorrow I'm going to send a pull request with what I came up with. We'll see how much of it can be used in your parallel code.

**Comment by andronat** [comment]
@Eipifi cool, waiting forward!

**Comment by bogdan-kulynych** [comment]
So, benchmarks: #6

**Comment by OmeGak** [comment]
We we'll come back to parallelization in the future, but since now we are writing the code in C++ and using another encryption scheme I'm closing this issue.
