### ISSUE TITLE
Implement V-DGHV somewhat homomorphic scheme

### ISSUE THREAD

**Issue by bogdan-kulynych** [blindstore/blindstore#21]
It appears that the V-DGHV scheme proposed in [Single-Database PIR from FHE](http://www.computer.org/csdl/trans/tk/2013/05/ttk2013051125-abs.html) allows for significant performance boost compared to using FHE as a black box. Using this scheme, we don't need to encrypt the indexes.

To achieve this, we need to marry PIR protocol to this particular HE scheme, so no abstraction on HE is needed anymore.

**Comment by OmeGak** [comment]
Done in https://github.com/blindstore/libshe
