### ISSUE TITLE
Investigate possible bug in set call

### ISSUE THREAD

**Issue by HarryCutts** [blindstore/blindstore#4]
During the demos, a set call for row 1 appeared to change two rows (1 and 2) in the database, as displayed on the Web display. I attempted (in a very short and hurried period of time) to reproduce the error on master, but could not. We need to discover whether this was an issue with the demo Web display, changes on the demo branch, or an issue with master.

**Comment by bogdan-kulynych** [comment]
No, it looks like only the first row was changed: http://training-molina.cern.ch/ and that was the expected behavior.

**Comment by HarryCutts** [comment]
But we definitely saw it when preparing on Sunday afternoon, didn't we?

**Comment by Eipifi** [comment]
Yes, I saw it too - two middle rows changed. However, this seems to be a bug with demo/server/client communication, not the server itself.

**Comment by HarryCutts** [comment]
Well, I just checked this out on master (four sets on different rows of a four-row database), and couldn't reproduce it. If it's an intermittent bug, it'll rear its head sooner or later. Until then, I'll close the issue.
