### ISSUE TITLE
Easier installation process

### ISSUE THREAD

**Issue by OmeGak** [blindstore/blindstore#7]
We should work on this before going public

**Comment by HarryCutts** [comment]
If this is going to be a target, we need some more specifics. What does 'easy' mean? `sudo apt install blindstore` and go, easy? What deployment process do we want, on what OSes?

Since those deploying Blindstore are pretty much guaranteed to be developers, I think a tarball which one can `make` and `make install` would be sufficient. Debian, RPM, Brew and Windows packages would be nice, obviously, but that could turn into a lot of work.

**Comment by OmeGak** [comment]
`pip install`?

**Comment by HarryCutts** [comment]
I don't really know much about packaging, but I'm guessing `pip` is best for Python, so I'm not sure how nicely it would play with other languages. For example, there might not be the dependencies we need in the pip repositories. But this is mostly speculation.

**Comment by OmeGak** [comment]
I like that stuff, so I'll be glad to investigate a bit.

**Comment by bogdan-kulynych** [comment]
We need to decouple Blindstore server libraries from Blindstore server _Flask server_, and only package libraries to pip. I think it's the right way to do it. 

For server development deployment

```
git clone <repo>
pip install -r requirements.txt
./manage.py runserver
```

Might be good enough for now.

Then we can make system package to launch it like mysql or postgres daemon.

**Comment by OmeGak** [comment]
Why are you guys against of installing the whole thing through `pip`? [ZODB](https://pypi.python.org/pypi/ZODB/4.0.1), for example, does it.

**Comment by HarryCutts** [comment]
ZODB is a Python library, so it makes sense to install it through pip. The Blindstore Flask server itself isn't a Python library, it's just written in Python.

**Comment by davidek** [comment]
Still, I believe pip packaging is convenient for installing any python package, be it a library or a server program.I would suggest
- pip packaging + pypi  for libs
- pip packaging without pypi for server and client (installable via `pip install git://whatever`)

**Comment by andronat** [comment]
Hi, usually when we are talking about services, we are packaging everything through rpm/deb packages. I believe that the best approach would be to separate the project into:
- internals => those can be libs (also test included) and pack them with pip or what ever
- services => like the Flask server, that has to be deployed and integrated with the targeted OS. This means rpm for RHEL and deb for Debian. Also we need to include init.d scripts that manage the application and not have local references to Flask internals

**Comment by OmeGak** [comment]
Closing because this fits more into the idea of blindstore wrappers that we develop further in the future once the cpp library is completed.
