### ISSUE TITLE
Random performance

### ISSUE THREAD

**Issue by Eipifi** [blindstore/blindstore#8]
Request execution can take from 0.22s to 12s. We must find out what causes this nondeterministic behaviour. Possible suspects:
- serialization (unlikely)
- python-C communication layer (unlikely)
- error in Flask (very unlikely)
- inherently unstable performance of the homomorphic operations or encryption/decryption (need to benchmark directly in C)

![image](https://cloud.githubusercontent.com/assets/2813061/3825055/aa80e06a-1d4f-11e4-94aa-364a9e6e99cf.png)

Request times (100 iterations):

``` 2.3899999999999997
9.07
0.7799999999999994
12.35
7.059999999999999
4.390000000000001
12.230000000000004
2.1299999999999955
0.21999999999999886
0.22000000000000597
1.0399999999999991
3.289999999999999
1.0300000000000011
2.0700000000000003
4.289999999999999
5.590000000000003
0.8599999999999994
0.6700000000000017
2.559999999999988
0.7400000000000091
7.670000000000002
5.359999999999999
4.239999999999995
2.3700000000000045
3.019999999999996
8.019999999999996
9.429999999999993
6.8500000000000085
2.8799999999999955
1.4500000000000028
1.5600000000000023
9.649999999999991
7.740000000000009
0.37999999999999545
0.27000000000001023
0.4099999999999966
1.2299999999999898
3.539999999999992
0.6500000000000057
0.27000000000001023
1.490000000000009
0.23999999999998067
0.28000000000000114
1.9399999999999977
5.670000000000016
7.6200000000000045
11.849999999999994
3.799999999999983
1.670000000000016
1.210000000000008
0.6599999999999966
6.189999999999998
1.3499999999999943
1.490000000000009
1.6999999999999886
3.0500000000000114
4.149999999999977
4.25
4.550000000000011
1.2299999999999898
1.990000000000009
2.490000000000009
3.7299999999999898
6.460000000000008
1.4099999999999966
8.25
2.75
9.960000000000008
1.8499999999999943
3.2199999999999704
2.2200000000000273
0.660000000000025
3.9799999999999613
0.9700000000000273
0.9599999999999795
4.1200000000000045
1.3600000000000136
0.9300000000000068
1.079999999999984
3.2799999999999727
8.260000000000048
0.9599999999999795
3.069999999999993
3.829999999999984
1.8199999999999932
2.1200000000000045
0.5299999999999727
1.2200000000000273
0.2999999999999545
3.3600000000000136
1.25
7.470000000000027
2.8700000000000045
0.5
2.3799999999999955
0.5299999999999727
2.519999999999982
1.8500000000000227
10.949999999999989
2.0300000000000296
```

**Comment by bogdan-kulynych** [comment]
Encryption is non-deterministic

**Comment by oddlord** [comment]
but the non-determinism is on the encrypted value returned, not on the execution time (or at least it should be)

**Comment by Eipifi** [comment]
Non-deterministic encryption != non-deterministic encryption performance. Pseudorandom number generators have stable performance. The difference is too big anyway.

**Comment by andronat** [comment]
Can you try to gather some input and manually isolate the encryption process into steps and try them separately?

Also, when you run the encryption algorithm multiple times, OS and even then CPU is doing a lot of clever stuff to optimize stuff around (because of the low level operations). So, there is a possibility to get major time improvements from those stuff.

**Comment by Eipifi** [comment]
I don't think low level optimizations could produce so random results. I run stable Debian, so this kind of stuff is surely not happening.

I'm going to split the process into separate parts and benchmark each part separately.

**Comment by Eipifi** [comment]
Got it. The issue seems to be related to the key pair generation process. The execution time may vary from 0.2s to even 25s. The problem must be related to libscarab, and there is little we can do about it right now.

All in all, it could be worse - once the client generates a key pair, all requests can be done relatively quickly.

Related benchmark: https://github.com/Eipifi/blindstore/blob/benchmarks/benchmarks/benchmark_key_generation.py

**Comment by davidek** [comment]
Could it be a matter of entropy collection? @Eipifi if you are still running from your virtual machine this is pretty likely (try running benchmarks and then run `ssh-keygen` and see how much time it takes)
