### ISSUE TITLE
Investigate possible adaptation of the schema to integer indices

### ISSUE THREAD

**Issue by davidek** [blindstore/blindstore#9]
Following up from #3, check whether it is feasible to port the protocol to support integer indices, instead of being forced to convert to binary and encrypt bit by bit.

**Comment by davidek** [comment]
There may actually be a way to do it: given that we have negation, if we redefine gamma as ![equation](http://latex.codecogs.com/gif.latex?%5Cgamma_j%20%3D%20%5Chat%7B1%7D%20&plus;%20%5Chat%7B%5Calpha%7D-%20%5Chat%7B%5Cbeta_%7Bj%7D%7D) it should work in a similar manner.

Still, I don't know if this is still as secure as the schema in the paper: could dig a little more, if this is interesting for the project, i.e. if we don't force the bit-by-bit API

Also, before digging more I guess we should check performance of encrypting one integer vs array of bits in HElib.

**Comment by Eipifi** [comment]
Are you sure? Assuming that ![alpha](http://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20%5Chat%7B%5Calpha%20%7D) and ![alpha](http://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20%5Chat%7B%5Cbeta%20%7D) are encrypted integers, we could recieve a value outside of ![](http://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20%5C%7B0%2C%201%5C%7D) range. That would make the output of the R() function invalid, as we need to multiply it by the integer value inside the matrix. Correct me if I'm wrong.

What would do is a 'greater than' operation (![](http://latex.codecogs.com/gif.latex?GT%5C%28%5Cmathbb%7BN%7D%5Ctimes%20%5Cmathbb%7BN%7D%29%20%5Crightarrow%20%5C%7B0%2C%201%5C%7D)) or any operation for comparing the value to zero, but I did not see support for any operation aside from addition and multiplication.

About checking HElib performance - yes, definetely. If we stick to @bogdan-kulynych 's idea of using modulo 2 integer space, we must check if we get any performance boost on the low level.

**Comment by bogdan-kulynych** [comment]
Yes, it's not that easy. We need a kind of homomorphic [Kronecker's delta](https://en.wikipedia.org/wiki/Kronecker_delta) for that.

**Comment by Eipifi** [comment]
Given SHIFT, XOR and AND operations (present in HElib), we can create the 'not equal to zero' operation:

Assuming we have a 32bit unsigned integer v:

```
for(i=0;i<32;++i){
    v = (v >> 1) | v;
}
v = v & 1;
```

OR can be implemented using AND and XOR.

I think we have it. The question is: can we afford the loop?

**Comment by bogdan-kulynych** [comment]
Yep, but it's even worse. Now we are performing two XORs 32 times on encrypted _bits_ for each index, and this algorithm is performing XORs and ORs 32 times on _encrypted 32-bit integers_ for each index.

**Comment by Eipifi** [comment]
Exactly. Therefore, unless we get a FHE with comparison operation, we need to deal with bits.

**Comment by davidek** [comment]
Mhm I was so wrong... I guess sticking to the bits would be the best choice, then

**Comment by bogdan-kulynych** [comment]
Closing for now, the proposed scheme looks good.
